plugins {
    id 'java-library'
}

group = 'dev.regionlib'
version = '0.1.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
    maven {
        url = 'https://repo.papermc.io/repository/maven-public/'
    }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:26.2.build.119-stable'
}

testing {
    suites {
        test {
            useJUnitJupiter()
        }
    }
}
